### ISSUE TITLE
expose command not found?

### ISSUE THREAD

**Issue by scratchoo** [beyondcode/expose#104]
```
composer --version
Composer version 1.10.9 2020-07-16 12:57:00
```

installation:

`composer global require beyondcode/expose`

Second time outpout:

```
composer global require beyondcode/expose
Changed current directory to /root/.composer
Using version ^1.0 for beyondcode/expose
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
1 package you are using is looking for funding.
Use the `composer fund` command to find out more!
```
trying expose command:

```
expose serve my-domain.com
-bash: expose: command not found
```

**Comment by MarvelousMari** [comment]
You need to move your expose composer file to somewhere in your PATH. For me I moved my expose file from
`/home/marvelousmari/.config/composer/vendor/beyondcode/expose/builds/expose`
to
`/usr/bin/`
if you can't find `./.config/` then you can use `ctrl+h` while in your file explorer or use `ls -a` in terminal

the alternative to this is to add where it already is to your system's PATH variable. To do that just do
`$ PATH=${PATH}:XXXXXXXX` where XXXXXXXX is the location of the folder containing the expose build (do not have other items in this folder or path unless you want to use those files as commands everywhere).

**Comment by CDRO** [comment]
You can update your `$PATH` variable like this:

```
PATH=~/.composer/vendor/bin:$PATH
echo PATH=$PATH >> ~/.bashrc
```

**Comment by scratchoo** [comment]
Thank you guys, it worked but another error now lol

```
In Factory.php line 213:
                                
  syntax error, unexpected ')' 
```

**Comment by MarvelousMari** [comment]
Can you post the contents of your Factory.php file? I ran across this issue before... I think you should take this at face value. The line should be: `$this->app->route('/socket', new WsServer(new Socket()), ['*']);`

**Comment by CDRO** [comment]
> 
> 
> Can you post the contents of your Factory.php file? I ran across this issue before... I think you should take this at face value. The line should be: `$this->app->route('/socket', new WsServer(new Socket()), ['*']);`

I've ran into the same issue.

The problem is, that the factory has a feature from PHP 7.3: trailing commas in parameter lists. As expose should only depend on PHP 7.2.5 according to the composer.json, you should not see that but, alas, it is in there.

You can work around this issue by using PHP 7.3 (hopefully you can install it or have a way to run it). Usually, if you run on a webhost, you should be able to start expose also by running `php7.3 expose serve your-domain.com`, therefore starting expose with PHP 7.3 instead of your default PHP version.

Best Regards

**Comment by dennisong45** [comment]
I'm having the same error.. I moved my expose to /usr/bin like MarvelousMari but no luck.

**Comment by dennisong45** [comment]
> You can update your `$PATH` variable like this:
> 
> ```
> PATH=~/.composer/vendor/bin:$PATH
> echo PATH=$PATH >> ~/.bashrc
> ```

Do you mind showing a some more details? Newbie here..thank you

**Comment by CDRO** [comment]
@dennisong45 What is your current PHP Version?

**Comment by dennisong45** [comment]
> @dennisong45 What is your current PHP Version?

7.4

**Comment by CDRO** [comment]
I can see, why this issue would arise:
https://github.com/beyondcode/expose/blob/master/app/Server/Factory.php#L212
This [should be covered in PHP 7.3](https://laravel-news.com/php-trailing-commas-functions) (and therefore 7.4), maybe it's a problem in PHP. What version *exactly* do you use right now?

It's also possible that if you have multiple versions of PHP installed, the version in `$PATH` is not the same as set in your environment for some reason and seeing as `expose` [uses the PHP version provided by you environment](https://github.com/beyondcode/expose/blob/master/expose#L1), this might be the reason why it does not work.

What happens if you run `php ./expose`?

**Comment by mpociot** [comment]
This is not an issue with Expose itself. Make sure that the binary/phar is accessible in a path that you have available in your PATH environment variable.

**Comment by auwsom** [comment]
2022 this has changed to `/home/user/.config/composer/vendor/bin/expose`

**Comment by opeen** [comment]
same problem  expose: command not found

**Comment by auwsom** [comment]
I ended up using Cloudflare tunnel. It's free now.

**Comment by daslicht** [comment]
still present in 2023

**Comment by kingzamzon** [comment]
> > You can update your `$PATH` variable like this:
> > ```
> > PATH=~/.composer/vendor/bin:$PATH
> > echo PATH=$PATH >> ~/.bashrc
> > ```
> 
> Do you mind showing a some more details? Newbie here..thank you
> 
> Edit: I got it to be working with PATH=${PATH}:/home/myserver-1/.config/composer/vendor/bin
> 
> Somehow the URL given does not work even I use expose on the directory of my webpage..

Thank you for sharing this. 
`myserver-1` should be replaced with user
