### ISSUE TITLE
Docker-compose for running expose server has wrong port mapping

### ISSUE THREAD

**Issue by cpxPratik** [beyondcode/expose#166]
On docker-compose file https://github.com/beyondcode/expose/blob/master/docker-compose.yml, port mapping with `127.0.0.1:8080:${PORT}` does not work in the context of separately provisioned Expose server.

I had to update it to `0.0.0.0:8080:${PORT}` or simply `8080:${PORT}` for Expose server to be able to listen to expose client's requests.

**Comment by mpociot** [comment]
Could you provide a PR for this?

**Comment by cpxPratik** [comment]
@mpociot Here is the PR, https://github.com/beyondcode/expose/pull/169

**Comment by tvercruysse** [comment]
This is actually wanted behavior when behind a reverse proxy, otherwise you can access the container by entering `ip:port` from the outside. Perhaps - as an alternative - a documentation update along the lines like this explains the situation better:

## Using expose without reverse proxy
1. When using the pre-build docker image, edit your docker-compose port section accordingly.

2. When tracking master create a new `docker-compose.override.yml` file with the following content:
```
version: "3.7"
services:
  expose:
    ports:
      - 8080:${port}
```
