### ISSUE TITLE
Assets/links being loaded from the "local" URL

### ISSUE THREAD

**Issue by xewl** [beyondcode/expose#19]
While exposing my local site, the local URL's are still being loaded from the local domain.

Eg.
```sh
$ expose share somelocal.site --subdomain=somelocalsite
[...]
Local-URL:              somelocal.site
Dashboard-URL:          http://127.0.0.1:4040
Expose-URL:             https://somelocalsite.sharedwithexpose.com
```

Shows the local site, but "somelocal.site" instances in source aren't rewritten to the Expose URL.

> Though, I might have missed something in the docs.

**Comment by mpociot** [comment]
Depending on how you load your assets, this could be an issue with your trusted proxy settings in your Laravel application.

**Comment by xewl** [comment]
Had to change `APP_URL` \ `ASSET_URL` to the expose URL & clear route caching. 
But, yeah.. changing that over all the time when I need to expose, feels a bit weird.
Proxy was default (config wasn't published), seems unrelated.

**Comment by sebdesign** [comment]
I had a similar issue with a laravel application on Valet. The local site is `example.test` and I'm loading the assets from `assets.example.test`, which is also linked on Valet.

E.g.:
```bash
expose share example.test --subdomain=example
```

When I'm loading `https://example.sharedwithexpose.com` none of the assets are loading due to mixed content, because Symfony doesn't think the request to this domain is secure (`Request::isSecure()` returns false). I believe that `https://example.sharedwithexpose.com` exposes `http://example.test` and not `https://example.test`, so the `HTTPS` server variable is not set.

Specifying the https scheme in the host argument does fix this:
```bash
expose share https://example.test --subdomain=example
```
