### ISSUE TITLE
Unable to use expose through custom domain

### ISSUE THREAD

**Issue by necrogami** [beyondcode/expose#338]
```
[2022-08-05 14:16:47] production.WARNING: explode(): Passing null to parameter #2 ($string) of type string is deprecated in phar:///usr/local/bin/expose/app/Client/Http/Modifiers/CheckBasicAuthentication.php on line 92
```
The php version is php 8.1.8

 launching expose returns this error and never loads the page

**Comment by daugaard47** [comment]
@necrogami  Getting this error too using php 7.4. Did you figure out the issue?

**Comment by necrogami** [comment]
I am still getting this error

**Comment by daugaard47** [comment]
@necrogami  Not sure if your issue is the same but I figured my issue out.
When expose starts, look at the Shared URL, it like this:
```
Shared URL:             mysite.test:443
Dashboard:              http://127.0.0.1:4040
Public HTTP:            http://mysite.us-1.sharedwithexpose.com
Public HTTPS:           https://mysite.us-1.sharedwithexpose.com
```

In my case I use Laragon and was using the prefix mysite.oo, then changed it to mysite.test.
Expose was still using Shared URL: mysite.oo.. So I ran `expose share --subdomain=mysite --server=us-1 https://mysite.test`

Now Expose uses Shared URL: mysite.test:443

However.. I still get the Warning on startup

> production.WARNING: explode(): Passing null to parameter 2 ($string) of type string is deprecated in phar://C:/Users/myname/AppData/Roaming/Composer/vendor/beyondcode/expose/builds/expose/app/Client/Http/Modifiers/CheckBasicAuthenticati

But I can now use my webhooks with no issue. 
Hope that helps.

**Comment by daugaard47** [comment]
Well looks like the error was a bug. Has been fixed in latest release.
