### ISSUE TITLE
Trying to read .env files?

### ISSUE THREAD

**Issue by haleyngonadi** [beyondcode/expose#362]
I've been using Expose Pro for a while now and I love it as it helps with local development. But I just noticed that when my local environment (built on Laravel) is exposed, something tries to read my .env file (even though that isn't called at all. It tries this in many directories too. Is this normal?

![Screen Shot 2023-01-11 at 01 01 24](https://user-images.githubusercontent.com/6877114/211729440-55b46315-0cc7-4a4b-8abe-e33c0d278ba8.png)

**Comment by isokcevic** [comment]
Bumping this, as another pro user.. This is a very bad look, especially with silence from the dev.

Some of the originating IPs can be found on blacklists when googling as well. 

I am stopping usage of this tool until a reasonable explanation for this behavior is provided. Wrote to support as well.

**Comment by sschlein** [comment]
Hi all, this is actually the open yource repository of the client and *please* raise these types of issues via our support inbox so that we can answer them quickly.

While we are looking into ways to block requests based on a IP list, these are typical requests of malicious bots that scan random URLs on the internet. If you check the logs of your normal web server of your application, you'll also find them. Luckily, Laravel is secure enough by default that this is not an issue and more an annoyance.

So if you encounter these scans, please create a support ticket by emailing us the information, your subdomain at that time and the Expose server region to support@beyondco.de and we'll block the IP for future requests asap.

I am closing this ticket because that's not an issue in this repository here but with the global network that we manage. If you come to this issue via a google search, please raise a support ticket via email with the requested information.

Thanks

**Comment by sschlein** [comment]
To give you even more information:

There are sites that monitor certificates that are created by let's encyrpt. They publish them for transparency reasons and all certificates that you create with them are also monitored. Sites like https://leakix.net/ use this data to automatically scan all sites that use these certificates and this is why you sometimes get requests from them.

As mentioned, we've working on solutions to block their bots but there is like an infinite number of services like this and so it's quite hard to block all of them.
